version: '3'

services:
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bn_keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bitnami_keycloak    
